version: "3.7"
services:
  em-mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    container_name: em-mysql
    networks:
      - em-network
    ports:
      - "33061:3306"
    expose:
      - 3306
    volumes:
      - ./data_dir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    cap_add:
      - SYS_NICE

  em-db-migration:
    build:
      context: .
      dockerfile: ./database/migrations/Dockerfile
    image: em-db-migration
    container_name: em-db-migration
    networks:
      - em-network
    depends_on:
      - em-mysql

  # em-db-seeder:
  #   build:
  #     context: .
  #     dockerfile: ./database/seeders/Dockerfile
  #   image: em-db-seeder
  #   container_name: em-db-seeder
  #   networks:
  #     - em-network
  #   depends_on:
  #     - em-mysql
  #     - em-db-migration

  em-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: em-api
    container_name: em-api
    networks:
      - em-network
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - em-mysql

networks:
  em-network:
    name: em-network
    driver: bridge
